# Generated by Django 5.0.2 on 2024-02-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='default.png', upload_to='thumbnails'),
        ),
    ]
