# Generated by Django 5.0.2 on 2024-02-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_category_tags_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='blogapp.tags'),
        ),
    ]
